kind: pipeline
type: docker
name: default

steps:
  - name: pypi_publish
    image: plugins/pypi
    settings:
      username:
        from_secret: pypi_username
      password:
        from_secret: pypi_password

node:
  location: local

trigger:
  event:
    - tag
